#!/bin/bash
# Search through open programs and switch to their tag

lock() {
    #blurlock
    /usr/bin/betterlockscreen --lock
}

options="lock\nlogout\nswitch_user\nsuspend\nhibernate\nreboot\npoweroff"
action=$(
    echo -e $options | \
    # Pipe to dmenu ($@ to include font settings from dwm/config.h)
    # dmenu -i -p "Switch to" $@
        rofi -dmenu -p "Whicht action?"
)

case "$action" in
    lock)
        lock
        ;;
    logout)
        i3-msg exit
        ;;
    switch_user)
        dm-tool switch-to-greeter
        ;;
    suspend)
        if [ $(cat /proc/1/comm) = "systemd" ]; then
            betterlockscreen --suspend
        else
            lock && dbus-send --system --dest=org.freedesktop.ConsoleKit --type=method_call --print-reply --reply-timeout=2000 /org/freedesktop/ConsoleKit/Manager org.freedesktop.ConsoleKit.Manager.Suspend boolean:true
        fi
        ;;
    hibernate)
        if [ $(cat /proc/1/comm) = "systemd" ]; then
            lock && systemctl hibernate
        else
            lock && dbus-send --system --dest=org.freedesktop.ConsoleKit --type=method_call --print-reply --reply-timeout=2000 /org/freedesktop/ConsoleKit/Manager org.freedesktop.ConsoleKit.Manager.Hibernate boolean:true
        fi
        ;;
    reboot)
        if [ $(cat /proc/1/comm) = "systemd" ]; then
            systemctl reboot
        else
            dbus-send --system --print-reply --type=method_call --reply-timeout=2000 --dest=org.freedesktop.ConsoleKit /org/freedesktop/ConsoleKit/Manager org.freedesktop.ConsoleKit.Manager.Restart
        fi
        ;;
    poweroff)
        if [ $(cat /proc/1/comm) = "systemd" ]; then
            systemctl poweroff
        else
            dbus-send --system --print-reply --type=method_call --reply-timeout=2000 --dest=org.freedesktop.ConsoleKit /org/freedesktop/ConsoleKit/Manager org.freedesktop.ConsoleKit.Manager.Stop
        fi
        ;;
    *)
        echo "== ! i3exit: missing or wrong argument ! ==
Try again with: lock | logout | switch_user | suspend | hibernate | reboot | shutdown"
        exit 2
esac
